### ISSUE TITLE
Staging and Tracking fo files in a child directory fails

### ISSUE THREAD

**Issue by GregOnNet** [agross/git_shizzle#3]
Hi Alex,

after updating to quick-git `0.2.8` I unfortunately get the following error when I use `quick-git track` or `quick-git stage` from a directory which is not the repository root.

![fullscreen_06_04_15_17_32](https://cloud.githubusercontent.com/assets/444278/7006735/c6c78f32-dc83-11e4-8e15-47564cab09b2.png)

The path seems to be correct. Nevertheless git cannot find the file.
I am working with Mac OSX.

Kind regards
Gregor

**Comment by agross** [comment]
What's the output of `type qn`?

**Comment by GregOnNet** [comment]
I get this:

```
± qn 1 // same as: quick-git track 1
git add -- "tasks/a.txt"
fatal: pathspec 'tasks/a.txt' did not match any files
git add -- "tasks/a.txt":false
```

**Comment by agross** [comment]
Please answer my question ;-)

``` bash
$ type qn
qn is an alias for git qn
```

**Comment by GregOnNet** [comment]
Aah sorry, I got it wrong.

``` sh
$ type qn
qn is aliased to `quick-git track'
```

**Comment by agross** [comment]
Alright. `qn` needs to be a git alias, as these are always run from the root of the repo. This should fix your issues with using `quick-git` inside subdirectories.

**Comment by GregOnNet** [comment]
Thanks, this works for me!
